
# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/theinaf8/public_html/
#     - /bin/cp -fr * $DEPLOYPATH


---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theinaf8/public_html/
    - /bin/rm -r * $DEPLOYPATH
    - /bin/mkdir test * $DEPLOYPATH
    - /bin/cp -fr * $DEPLOYPATH
    
# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/cpanelUserName/public_html
#     - /bin/cp * $DEPLOYPATH
#     - /bin/cp/ -r * $DEPLOYPATH
#     - /bin/chmod 755 ${DEPLOYPATH}
#     - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
#     - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
